# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2364775c78a6c12d0c2437e84fcbc520d0106ad7fb85339b56871bb8e4fee30857d74f0b455e9dfac65b6b97cef6b32dec6a42ac3e81c67be841a1bfda896da

test:
  secret_key_base: 48e58dfe708efd60c386accff2792d86330446a5da1288577c205bc465409002dfdeb6735ad64d96d9e52e3c57eae619c950523b3d0318c8ac2d539c984be4ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
